# Generated by Django 3.1.6 on 2021-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_task',
            fields=[
                ('ticketid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('priority', models.CharField(max_length=4)),
                ('start_date', models.DateTimeField(blank=True, max_length=255)),
                ('end_date', models.DateTimeField(blank=True, max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('splice_num', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('north', models.CharField(blank=True, max_length=255)),
                ('west', models.CharField(blank=True, max_length=255)),
                ('circuits', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
