# Generated by Django 3.1.6 on 2021-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cudb', '0002_ticket_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_task',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
